site_name: SUNRISE
summary: 该网站是SUNRISE 官网后台管理系统说明文档
authors: Andy
date: 2018-12-23
theme: readthedocs
nav:
    - '开始': 'index.md'
    - '页面-主页': 'homepage.md'
    - '页面-关于': 'aboutpage.md'
    - '页面-解决方案': 'solutions.md'
    - '页面-新闻资讯': 'news.md'
    - '页面-方案展示': 'cases.md'
    - '页面-团队': 'team.md'
    - '页面-招聘': 'job.md'
    - '功能-联系我们': 'contact.md'